version: '3'

services: 
  biochain:
    build:
      dockerfile: Dockerfile
      context: .
    image: bc_converter
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - 3000:3000
    volumes:
      - "./:/home"