version: '3'

services: 
  biochain:
    build:
      dockerfile: Dockerfile
      context: .
    image: biochain 
    command: sh -c "sh ./run.sh"
    ports:
      - 3000:3000
    volumes:
      - "./:/home"
      - "./content:/home/content"
      - "./content/imports:/home/content/imports"
      - "./upload-svs:/home/upload-svs"
      - "./server-middleware/uploads:/home/server-middleware/uploads"
      - "./run.sh:/home/run.sh"