version: '3'

services: 
  biochain:
    build:
      dockerfile: Dockerfile
    image: bc_converter
    ports:
      - 3000:3000
    command: sh -c "cd home && npm run dev"
    volumes:
      - "./:/home"