version: '3'

services:
  node:
    image: node:14
    build:
      context: .
    command: sh -c "cd home/node/app && npm run dev" 
    ports:
      - "3000:3000"
    volumes:
      - "./:/home/node/app"
      - "./node_modules:/home/node/app/node_modules"